//
// Created by Administrator on 2023-02-08.
//

#ifndef $TVM_SRC_SHARE_CODEFILE_TEAFILEREADER_HPP
#define $TVM_SRC_SHARE_CODEFILE_TEAFILEREADER_HPP


class TeaFileReader {

};


#endif //$TVM_SRC_SHARE_CODEFILE_TEAFILEREADER_HPP
